from enum import Enum

class GovernanceAction(Enum):
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    OVERRIDE_MODE = "OVERRIDE_MODE"
    LOCK_AUTONOMY = "LOCK_AUTONOMY"
    UNLOCK_AUTONOMY = "UNLOCK_AUTONOMY"
    IMPOSE_CONSTRAINT = "IMPOSE_CONSTRAINT"
    LIFT_CONSTRAINT = "LIFT_CONSTRAINT"