from typing import List
from src.core.domain.intention import Intention
from src.core.domain.behavior import BehaviorState


class IntentionPressureService:
    """
    Pure service. Calculates the pressure delta generated by existing intentions.
    Intentions create background tension that increases readiness.
    """

    def calculate_pressure(
            self,
            intentions: List[Intention],
            state: BehaviorState
    ) -> float:
        if not intentions:
            return 0.0

        # 1. Base Pressure from Intentions
        # Sum of priorities scaled down
        base_pressure = sum(i.priority for i in intentions) * 0.3

        # 2. Fatigue Factor
        # High fatigue dampens the pressure (too tired to care)
        # Fatigue 0 -> factor 1.0
        # Fatigue 100 -> factor 0.2
        fatigue_factor = max(0.2, 1.0 - (state.fatigue / 100.0))

        # 3. Energy Factor
        # Low energy reduces pressure perception
        # Energy 100 -> factor 1.0
        # Energy 0 -> factor 0.3
        energy_factor = max(0.3, state.energy / 100.0)

        # 4. Calculate Delta
        pressure_delta = base_pressure * fatigue_factor * energy_factor

        # Cap the delta to prevent explosion
        return min(10.0, pressure_delta)